env:
  browser: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    modules: true
extends:
  - "eslint:recommended"

rules:
  no-const-assign: error
  no-duplicate-imports: error
  no-unreachable: error
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  no-console: error
  no-empty: error
  no-extra-semi: error
  multiline-comment-style:
    - error
    - starred-block

overrides:
  - files:
      - "files-to-sync/cli/**"
      - "files-to-sync/deployment/**"
    rules:
      no-console: off
