# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  prchecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Configure pre-commit to skip irrelevant checks
        run: echo "SKIP=typescript-check-cli,typescript-check-api,typescript-check-ui" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.1
  assignAuthor:
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assign PR to Creator
        run: gh pr edit $PRNUM --add-assignee $PR_AUTHOR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
