name: PR Notification

on:
  pull_request:
    types: [opened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  setup:
    name: Checkout repo
    uses: ./.github/workflows/checkout-repo.yml

  notify_integrations_channel:
    name: Notify integrations channel
    if: >
      github.actor != 'dependabot[bot]' &&
      github.actor != 'github-actions[bot]' &&
      github.actor != 'mdct-github-service-account' &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
    env:
      MSG_MINIMAL: true
      SLACK_MESSAGE: |
        ${{ github.event.pull_request.html_url }}
        Cloudfront URL: N/A
      SLACK_TITLE: |
        :github: A new pull request has been created in ${{ github.repository }} by ${{ github.event.pull_request.user.login }}
      SLACK_WEBHOOK: ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}
