name: Publish Package to npmjs
on:
  push:
    branches:
      - publish-changes
jobs:
  build:
    runs-on: ubuntu-latest
    # gives temp GITHUB_TOKEN without setting in github actions secrets explicitly
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      # Sets up .npmrc file to publish to npm, using NODE_AUTH_TOKEN environment variable
      # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: yarn
      - run: yarn build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
