name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # gives temp GITHUB_TOKEN without setting in github actions secrets explicitly.
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: yarn
      - run: yarn build
      - run: |
          npx semantic-release
          version=$(git describe --tags)
          echo "version_published=$version" >> $GITHUB_ENV
      - run: |
          echo "npm version published: ${version_published}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  notify_on_release:
    runs-on: ubuntu-latest
    needs: 
      - build
    if: ${{ success() && needs.build.outputs.version_published }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://img.shields.io/npm/v/@enterprise-cmcs/mdct-core/latest.svg
          SLACK_TITLE: A new version of mdct-core has been published to NPM
          SLACK_USERNAME: ${{ github.repository }} - ${{job.status}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}