name: Publish Package to npmjs
on:
  push:
    branches:
      - publish-changes
jobs:
  build:
    runs-on: ubuntu-latest
    #gives temp GITHUB_TOKEN
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      # Sets up .npmrc file to publish to npm, using NODE_AUTH_TOKEN environment variable
      # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      # - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
