name: Publish Package to npmjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # gives temp GITHUB_TOKEN without setting in github actions secrets explicitly.
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: yarn
      - run: yarn build
      - run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  notify_on_release:
    runs-on: ubuntu-latest
    needs: 
      - build
    if: ${{ github.event_name == 'push' && (startsWith(github.event.head_commit.message, 'fix') || startsWith(github.event.head_commit.message, 'feat') || startsWith(github.event.head_commit.message, 'perf')) }}
    steps:
      - name: Get Core Version
        id: get_version
        run: |
          echo "VERSION=$(npm show @enterprise-cmcs/mdct-core version)" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/14.0/apple-medium/1f680@2x.png
          SLACK_TITLE: "A new version of @enterprise-cmcs/mdct-core ** (${{ env.VERSION}}) ** has been published to NPM."
          SLACK_USERNAME: ${{ github.repository }} - ${{job.status}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  notify_on_build_failure:
    runs-on: ubuntu-latest
    needs: 
      - build
    if: failure()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{job.status}}
          SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/14.0/apple-medium/1f680@2x.png
          SLACK_TITLE: "The latest Core Build Has Failed"
          SLACK_USERNAME: ${{ github.repository }} - ${{job.status}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}