name: Sync Files Across MDCT Apps

on:
  schedule:
    # Every day at 6AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get GitHub App token
        id: app-token-step
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Run sync script
        run: node sync-files-github.ts
        env:
          GITHUB_TOKEN: ${{ steps.app-token-step.outputs.token }}
